from fastapi import APIRouter, HTTPException, status, Depends
from pydantic import BaseModel, Field, validator
from typing import Optional
from sqlalchemy.orm import Session

from app.services.question_generator import question_generator
from app.core.logging import logger
from app.db.database import get_db
from app.models.models import Assessment
from app.workers.celery_work import async_generate_questions
from app.core.security import get_current_user, require_role
from app.models.user import UserRole

router = APIRouter()


class AssessmentRequest(BaseModel):
    topic: str = Field(..., min_length=3)
    difficulty: str = Field(...)
    num_students: int = Field(..., gt=0, le=100)
    base_seed: Optional[int] = Field(42)
    use_async: bool = Field(False)


@router.post("/generate", response_model=dict)
async def generate_assessment(
    request: AssessmentRequest,
    db: Session = Depends(get_db),
    current_user: dict = Depends(require_role(UserRole.teacher))   # Only teachers & admins
):
    logger.info(f"Assessment generated by {current_user['email']} ({current_user['role']})")

    try:
        if request.use_async:
            task = async_generate_questions.delay(
                request.topic, request.difficulty, request.num_students
            )
            return {
                "message": "Assessment queued successfully",
                "task_id": task.id,
                "generated_by": current_user['email']
            }

        questions = question_generator.generate_for_students(
            topic=request.topic,
            difficulty=request.difficulty,
            num_students=request.num_students,
            base_seed=request.base_seed
        )

        assessment = Assessment(
            topic=request.topic,
            difficulty=request.difficulty,
            questions=questions
        )
        db.add(assessment)
        db.commit()

        return {
            "topic": request.topic,
            "difficulty": request.difficulty,
            "total_students": request.num_students,
            "questions": questions,
            "generated_by": current_user['email']
        }

    except Exception as e:
        logger.exception("Assessment generation failed")
        raise HTTPException(status_code=500, detail=str(e))